# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e2cfaf52b2817e75c048634b869ccdc3ed6660259af5ac76349f3c3797c302bb43099dbf9a3083885b57c003b9c2f5602df7893dff3de1c210e2d40ab1d97ab

test:
  secret_key_base: b21ba6363d36f242a4604ecabc13439de66e7fd3de5d4541f0cafa6feb78bea0218adf8cbaa0dd887d4b71657f8d533144e50b357f93af9f59f6ca0e2c24fb3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
